package com.kevin.mellow.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kevin.mellow.database.CityManageEntity;
import com.kevin.mellow.database.CityDataEntity;

import com.kevin.mellow.database.CityManageEntityDao;
import com.kevin.mellow.database.CityDataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityManageEntityDaoConfig;
    private final DaoConfig cityDataEntityDaoConfig;

    private final CityManageEntityDao cityManageEntityDao;
    private final CityDataEntityDao cityDataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityManageEntityDaoConfig = daoConfigMap.get(CityManageEntityDao.class).clone();
        cityManageEntityDaoConfig.initIdentityScope(type);

        cityDataEntityDaoConfig = daoConfigMap.get(CityDataEntityDao.class).clone();
        cityDataEntityDaoConfig.initIdentityScope(type);

        cityManageEntityDao = new CityManageEntityDao(cityManageEntityDaoConfig, this);
        cityDataEntityDao = new CityDataEntityDao(cityDataEntityDaoConfig, this);

        registerDao(CityManageEntity.class, cityManageEntityDao);
        registerDao(CityDataEntity.class, cityDataEntityDao);
    }
    
    public void clear() {
        cityManageEntityDaoConfig.clearIdentityScope();
        cityDataEntityDaoConfig.clearIdentityScope();
    }

    public CityManageEntityDao getCityManageEntityDao() {
        return cityManageEntityDao;
    }

    public CityDataEntityDao getCityDataEntityDao() {
        return cityDataEntityDao;
    }

}
